--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/OreFactory
build-by-default: true
branches:
- stable
projects:
  OreFactory:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.2.3
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
      - src: terpz710/pocketforms/PocketForms
        version: ^1.0.0
    lint: false
...
